### Build a DNN using Keras with `RELU` and `ADAM`

#### Load tensorflow

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

#### Collect Fashion mnist data from tf.keras.datasets 

In [2]:
#import MNIST dataset
from keras.datasets import mnist

Using TensorFlow backend.


In [3]:
#Load the dataset
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [4]:
(X_train.shape, y_train.shape), (X_test.shape, y_test.shape)

(((60000, 28, 28), (60000,)), ((10000, 28, 28), (10000,)))

In [5]:
#Finding the unique values of the target variable
np.unique(y_train)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [6]:
# X_train has values up to 255. this needs to be normalised
np.unique(X_train)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

#### Change train and test labels into one-hot vectors & normalize data

In [7]:
#Normalising X_train and X_test
X_train = X_train/255
X_test = X_test/255

In [8]:
#checking if normalisation has worked
np.unique(X_train)

array([0.        , 0.00392157, 0.00784314, 0.01176471, 0.01568627,
       0.01960784, 0.02352941, 0.02745098, 0.03137255, 0.03529412,
       0.03921569, 0.04313725, 0.04705882, 0.05098039, 0.05490196,
       0.05882353, 0.0627451 , 0.06666667, 0.07058824, 0.0745098 ,
       0.07843137, 0.08235294, 0.08627451, 0.09019608, 0.09411765,
       0.09803922, 0.10196078, 0.10588235, 0.10980392, 0.11372549,
       0.11764706, 0.12156863, 0.1254902 , 0.12941176, 0.13333333,
       0.1372549 , 0.14117647, 0.14509804, 0.14901961, 0.15294118,
       0.15686275, 0.16078431, 0.16470588, 0.16862745, 0.17254902,
       0.17647059, 0.18039216, 0.18431373, 0.18823529, 0.19215686,
       0.19607843, 0.2       , 0.20392157, 0.20784314, 0.21176471,
       0.21568627, 0.21960784, 0.22352941, 0.22745098, 0.23137255,
       0.23529412, 0.23921569, 0.24313725, 0.24705882, 0.25098039,
       0.25490196, 0.25882353, 0.2627451 , 0.26666667, 0.27058824,
       0.2745098 , 0.27843137, 0.28235294, 0.28627451, 0.29019

In [9]:
# one hot encode of test and train labels
# We will have 10 classes for the 10 digits
from keras.utils import np_utils
number_of_classes = 10
y_train = np_utils.to_categorical(y_train, number_of_classes)
y_test = np_utils.to_categorical(y_test, number_of_classes)

In [10]:
#Checking the one hot encoded matrix to see if it is done
y_train[0:1]

array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]], dtype=float32)

#### Build the Graph

#### Initialize model, reshape

In [11]:
# 28*28 = 784
X_train = X_train.reshape(60000,784) 
X_test = X_test.reshape(10000,784)

In [12]:
X_train.shape, X_test.shape

((60000, 784), (10000, 784))

In [13]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.activations import relu,softmax
from keras.optimizers import Adam
from keras.metrics import categorical_crossentropy

In [14]:
#Initialize Sequential Graph (model)
model = Sequential()

#### Add two fully connected layers with 200 and 100 neurons respectively with `relu` activations. Add a dropout layer with `p=0.25`

In [15]:
#Add first Dense Layer which provides 200 Outputs after applying relu
model.add(Dense(200, activation='relu',input_dim=784)) 

#Add second Dense Layer which provides 100 Outputs after applying relu
model.add(Dense(100, activation='relu'))

# Add a drop out layer p=0.25
model.add(Dropout(0.25))

### Add the output layer with a fully connected layer with 10 neurons with `softmax` activation. Use `categorical_crossentropy` loss and `adam` optimizer and train the network. And, report the final validation.

In [16]:
# Output layer with 10 neuraons for the 10 classes and softmax activation
model.add(Dense(10, activation='softmax'))

In [17]:
# Compile model
model.compile(loss='categorical_crossentropy', optimizer='Adam', metrics=['accuracy'])

In [18]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 200)               157000    
_________________________________________________________________
dense_2 (Dense)              (None, 100)               20100     
_________________________________________________________________
dropout_1 (Dropout)          (None, 100)               0         
_________________________________________________________________
dense_3 (Dense)              (None, 10)                1010      
Total params: 178,110
Trainable params: 178,110
Non-trainable params: 0
_________________________________________________________________


In [19]:
# Fit the model
model.fit(X_train,y_train,epochs=7,verbose=2)

Epoch 1/7
 - 5s - loss: 0.2524 - acc: 0.9249
Epoch 2/7
 - 5s - loss: 0.1080 - acc: 0.9670
Epoch 3/7
 - 5s - loss: 0.0777 - acc: 0.9764
Epoch 4/7
 - 5s - loss: 0.0600 - acc: 0.9812
Epoch 5/7
 - 5s - loss: 0.0493 - acc: 0.9841
Epoch 6/7
 - 5s - loss: 0.0394 - acc: 0.9877
Epoch 7/7
 - 5s - loss: 0.0367 - acc: 0.9881


In [20]:
eval1_list=[]
eval1_list = model.evaluate(X_test, y_test)
print('Model Loss is',eval1_list[0])
print('Model Accuracy is',eval1_list[1])

10000/10000 [==============================] - 0s 35us/step
Model Loss is 0.10324646647359041
Model Accuracy is 0.9749
