## Train a simple convnet on the Fashion MNIST dataset

In this, we will see how to deal with image data and train a convnet for image classification task.

### Load the  `fashion_mnist`  dataset

** Use keras.datasets to load the dataset **

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
tf.__version__

'1.12.0'

In [2]:
tf.set_random_seed(42)
from keras.datasets import fashion_mnist
(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()

Using TensorFlow backend.


### Find no.of samples are there in training and test datasets

In [3]:
#Training Data
x_train.shape,y_train.shape 

((60000, 28, 28), (60000,))

In [4]:
x_test.shape,y_test.shape

((10000, 28, 28), (10000,))

In [5]:
#Checking number of classes / digits 
np.unique(y_train)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

### Find dimensions of an image in the dataset

In [6]:
x_train.shape

(60000, 28, 28)

### Convert train and test labels to one hot vectors

** check `keras.utils.to_categorical()` **

In [7]:
y_train = tf.keras.utils.to_categorical(y_train, num_classes=10)
y_test = tf.keras.utils.to_categorical(y_test, num_classes=10)

In [8]:
#Checking to ensure that one hot coding has worked
y_train

array([[0., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [9]:
#Checking to ensure that one hot coding has worked
y_test[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 1.], dtype=float32)

### Normalize both the train and test image data from 0-255 to 0-1

In [10]:
# Normalise to 0 to 1 by dicing by 250
x_train = x_train/250
x_test = x_test/250

In [11]:
#Checking to ensure normalisation is done 
x_train[0]

array([[0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.004, 0.   , 0.   , 0.052, 0.292, 0.   ,
        0.   , 0.004, 0.016, 0.   , 0.   , 0.   , 0.   , 0.004, 0.004,
        0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   

### Reshape the data from 28x28 to 28x28x1 to match input dimensions in Conv2D layer in keras

In [12]:
#Initialize Sequential Graph (model)
model = tf.keras.models.Sequential()

#Reshape data from 2D to 1D -> 28x28 to 784
model.add(tf.keras.layers.Reshape((784,),input_shape=(28,28,)))

### Import the necessary layers from keras to build the model

In [13]:
#Add first Dense Layer which provides 128 Outputs after applying softmax
model.add(tf.keras.layers.Dense(128, activation='relu'))

In [14]:
#Add Dense Layer which provides 10 Outputs after applying softmax
model.add(tf.keras.layers.Dense(10, activation='softmax'))

In [15]:
#Compile the model
model.compile(optimizer='sgd', loss='categorical_crossentropy', metrics=['accuracy'])

In [16]:
#Execute the Model
model.fit(x_train, y_train, epochs=10)

Epoch 1/10
60000/60000 [==============================] - 8s 128us/step - loss: 0.7322 - acc: 0.7643
Epoch 2/10
60000/60000 [==============================] - 7s 123us/step - loss: 0.5088 - acc: 0.8273
Epoch 3/10
60000/60000 [==============================] - 7s 115us/step - loss: 0.4647 - acc: 0.8396
Epoch 4/10
60000/60000 [==============================] - 7s 115us/step - loss: 0.4399 - acc: 0.8479
Epoch 5/10
60000/60000 [==============================] - 7s 120us/step - loss: 0.4218 - acc: 0.8546
Epoch 6/10
60000/60000 [==============================] - 7s 119us/step - loss: 0.4081 - acc: 0.8580
Epoch 7/10
60000/60000 [==============================] - 7s 121us/step - loss: 0.3958 - acc: 0.8628
Epoch 8/10
60000/60000 [==============================] - 7s 120us/step - loss: 0.3865 - acc: 0.8646
Epoch 9/10
60000/60000 [==============================] - 7s 125us/step - loss: 0.3778 - acc: 0.8687
Epoch 10/10
60000/60000 [==============================] - 7s 120us/step - loss: 0.3700 - a

In [17]:
#Evaluate the Model
eval2_list=[]
eval2_list = model.evaluate(x_test, y_test)
print('Model Loss is',eval2_list[0])
print('Model Accuracy is',eval2_list[1])

10000/10000 [==============================] - 1s 65us/step
Model Loss is 0.4076000749588013
Model Accuracy is 0.856


### Build a model 

** with 2 Conv layers having `32 3*3 filters` in both convolutions with `relu activations` and `flatten` before passing the feature map into 2 fully connected layers (or Dense Layers) having 128 and 10 neurons with `relu` and `softmax` activations respectively. Now, using `categorical_crossentropy` loss with `adam` optimizer train the model with early stopping `patience=5` and no.of `epochs=10`. **

### Now, to the above model add `max` pooling layer of `filter size 2x2` and `dropout` layer with `p=0.25` after the 2 conv layers and run the model

### Now, to the above model, lets add Data Augmentation 

### Import the ImageDataGenrator from keras and fit the training images

#### Showing 5 versions of the first image in training dataset using image datagenerator.flow()

In [ ]:
from matplotlib import pyplot as plt
gen = datagen.flow(x_train[0:1], batch_size=1)
for i in range(1, 6):
    plt.subplot(1,5,i)
    plt.axis("off")
    plt.imshow(gen.next().squeeze(), cmap='gray')
    plt.plot()
plt.show()

In [ ]:
fig,ax=plt.subplots(1,10)
fig.set_figheight(10)
fig.set_figwidth(100)
#axs[0,0].plt.imshow(trainX[3],cmap='gray')
for i in range(10):
    ax[i].imshow(x_train[i],cmap='gray')
    ax[i].set_title(y_train[i])

### Run the above model using fit_generator()

###  Report the final train and validation accuracy

## **DATA AUGMENTATION ON CIFAR10 DATASET**

One of the best ways to improve the performance of a Deep Learning model is to add more data to the training set. Aside from gathering more instances from the wild that are representative of the distinction task, we want to develop a set of methods that enhance the data we already have. There are many ways to augment existing datasets and produce more robust models. In the image domain, these are done to utilize the full power of the convolutional neural network, which is able to capture translational invariance. This translational invariance is what makes image recognition such a difficult task in the first place. You want the dataset to be representative of the many different positions, angles, lightings, and miscellaneous distortions that are of interest to the vision task.

### **Import neessary libraries for data augmentation**

### **Load CIFAR10 dataset**

### **Create a data_gen funtion to genererator with image rotation,shifting image horizontally and vertically with random flip horizontally.**

### **Prepare/fit the generator.**

### **Generate 5 images for 1 of the image of CIFAR10 train dataset.**